### PR TITLE
Added Favicon, fixed link and formatted code

### PR DESCRIPTION
**Pull request by bilalmirza74**
Accept This PR🚀 
by adding hacktoberfest and hactoper-accepted

before merge
Thanks

### CODE REVIEW

**Review by WebDevFreelancer — APPROVED** [review]
looking good Accept this one @mrvivacious

**Review by bilalmirza74 — COMMENTED** [review]
done 
check out live here
https://my-bhagavad-gita.netlify.app/

**Review by bilalmirza74 — COMMENTED** [review]
done bro

**Comment by mrvivacious** [comment]
Hi, lots of good stuff here.

However, to keep things organized, can this pull request only have the code related to the favicon?

And then a separate PR for the code formatting, and a separate one for any other details/changes...

I can create and assign to you a reformat issue with the hacktober stuff if you'd like.

**Comment by mrvivacious** [comment]
You have done a fantastic job so far btw :)

**Comment by mrvivacious** [comment]
favicon is good √

`<meta name="viewport" content="width=device-width, initial-scale=1.0">` is affecting mobile interface. dont worry about it. ill investigate that later.

that netlify link is cool. nice way to demo ! thanks for showing me that

**Comment by mrvivacious** [comment]
merged and added the labels. Thank you.

but yeah i would say next time, try to break up changes in different PRs. ie. "reformatting" should not introduce features or functionality. but i dont know hacktoberfest that much and this project is super simple (haha) so it's ok √√

**Pull request merged**
